name: Build Static Site

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run API and Generate Data
        run: |
          node app.js &
          sleep 5 # 等待 API 启动
          node scripts/generate-static.js # 生成静态文件

      - name: Compress Static Files
        run: |
          mkdir -p dist
          tar -czvf dist/static-site.tar.gz index.html static/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: dist/static-site.tar.gz
