name: Build Static Files

     on:
       push:
         branches:
           - main  # 触发构建的分支

     jobs:
       build:
         runs-on: ubuntu-latest

         steps:
           - name: Checkout code
             uses: actions/checkout@v3

           - name: Set up Node.js
             uses: actions/setup-node@v3
             with:
               node-version: 16  # 使用 Node.js 16

           - name: Install dependencies
             run: npm install

           - name: Build static files
             run: |
               mkdir -p public/api
               echo '{"result": "search data"}' > public/api/search.json
               echo '{"result": "song data"}' > public/api/song.json

           - name: Upload artifacts
             uses: actions/upload-artifact@v3
             with:
               name: static-files
               path: public
